apiVersion: v1
kind: Secret
metadata:
  name: node-health-watcher-secret
  namespace: monitoring
type: Opaque
stringData:
  AIRFLOW_USERNAME: change-me
  AIRFLOW_PASSWORD: change-me
  GHA_TOKEN: change-me
